version: '3.1'
services:
  mysql:
    env_file:
        - .env
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASS}}"
    ports: 
        - 3306:3306
    volumes:
        - ./volumes:/var/lib/mysql