version: '3.1'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --sql_mode="NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --group_concat_max_len=10000
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      TZ: "America/Sao_Paulo"
    volumes:
      - ./volumes:/var/lib/mysql
      # - ./conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    ports:
      - 3308:3306
