version: '3.1'
services:
  mysql:
    env_file:
        - .env
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports: 
        - 3306:3306
    volumes:
        - ./volumes:/var/lib/mysql
        - ./config/my.cnf:/etc/mysql/my.cnf